# Generated by Django 4.2.29 on 2026-07-13 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('credits', models.DecimalField(decimal_places=2, help_text='Credits granted', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='USD amount billed, if applicable', max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_issued', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='billing.credittransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='billing_inv_user_id_05e625_idx'), models.Index(fields=['created_at'], name='billing_inv_created_1e16da_idx'), models.Index(fields=['invoice_number'], name='billing_inv_invoice_70511c_idx')],
            },
        ),
    ]
