# Generated by Django 4.2.29 on 2026-04-12 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrubJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('filename', models.CharField(help_text='Original uploaded filename', max_length=255)),
                ('file', models.FileField(blank=True, upload_to='scrub_uploads/%Y/%m/')),
                ('scrub_types', models.JSONField(default=list, help_text='List of scrub types: federal_dnc, state_dnc, litigator, wireless, etc.')),
                ('total', models.PositiveIntegerField(default=0, help_text='Total numbers submitted')),
                ('clean', models.PositiveIntegerField(default=0, help_text='Numbers that passed all scrubs')),
                ('dnc', models.PositiveIntegerField(default=0, help_text='Federal DNC matches')),
                ('litigator', models.PositiveIntegerField(default=0, help_text='Litigator list matches')),
                ('state_dnc', models.PositiveIntegerField(default=0, help_text='State DNC matches')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='scrub_results/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrub_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='scrubber_sc_user_id_e37eb9_idx'), models.Index(fields=['user', 'status'], name='scrubber_sc_user_id_07b171_idx'), models.Index(fields=['job_id'], name='scrubber_sc_job_id_ece333_idx'), models.Index(fields=['created_at'], name='scrubber_sc_created_149f60_idx'), models.Index(fields=['status', 'created_at'], name='scrubber_sc_status_d1dcd8_idx')],
            },
        ),
    ]
