# Generated by Django 4.2.29 on 2026-04-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrubber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrubjob',
            name='error_message',
            field=models.TextField(blank=True, help_text='Set when status=failed'),
        ),
    ]
